version: '3'

services:
  run-test:
    image: docker-registry.lge.com/project/webos/webos-tv-unittest/base
    user: 'run-test'
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ./:/work
